export const REGISTER_SUCCESS='REGISTER_SUCCESS';
export const REGISTER_ERROR='REGISTER_ERROR';
export const CLEAN_ALERTS='CLEAN_ALERTS';

export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGIN_ERROR='LOGIN_ERROR';
export const SIGNOUT='SIGNOUT';

export const AUTHENTICATION_SUCCESS='AUTHENTICATION_SUCCESS';

export const SHOW_ALERT='SHOW_ALERT';

export const UPLOAD_FILE_SUCCESS='UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_ERROR='UPLOAD_FILE_ERROR';
export const CREATE_LINK_SUCCESS='CREATE_LINK_SUCCESS';
export const CREATE_LINK_ERROR='CREATE_LINK_ERROR';
export const LOADING_UPLOAD='LOADING_UPLOAD';

export const CLEAN_STATE='CLEAN_STATE';